const Router = require('express-promise-router')();
const ThaiController = require('../controllers/thai');
Router.get('/sell_ticket_ledgers', ThaiController.getSellTicketLedgers);
Router.get('/shop_sell_ticket_ledgers', ThaiController.getShopSellTicketLedgers);
Router.post('/ticket_ledgers', ThaiController.getTicketLedgers);
Router.post('/agent_sold_out_ticket_ledgers', ThaiController.getAgentSoldOutTicketLedgers);
Router.post('/agent_cash_ticket_ledgers', ThaiController.getAgentCashTicketLedgers);
Router.post('/check_agent_cash_ticket_ledgers', ThaiController.getCheckAgentCashTicketLedgers);
Router.get('/delete_ticket_ledgers', ThaiController.getDeleteTicketLedger);
Router.post('/sold_out_single_ticket', ThaiController.soldOutSingleTicket);
Router.post('/sold_out_multi_ticket', ThaiController.soldOutMultiTicket);
Router.post('/update_remark', ThaiController.updateRemark);
Router.post('/delete_ticket_ledger', ThaiController.deleteTicketLedger);
Router.post('/un_sell_ticket_ledger', ThaiController.unSellTicketLedger);
Router.post('/cash_ticket_ledger', ThaiController.cashTicketLedger);
Router.post('/cash_air_only_ticket_ledger', ThaiController.cashAirOnlyTicketLedger);
Router.get('/simple_price', ThaiController.getSimplePrice);
Router.post('/update_simple_price', ThaiController.updateSimplePrice);
Router.post('/sold_out_profit', ThaiController.getSoldOutProfit);
Router.post('/cash_profit', ThaiController.getCashProfit);
Router.post('/sold_out_pre_pay', ThaiController.soldOutPrePay);
Router.post('/cash_pre_pay', ThaiController.cashPrePay);
Router.post('/cash_balance', ThaiController.cashBalance);
Router.post('/close_tickets', ThaiController.closeTickets);
Router.get('/sell_active_tickets', ThaiController.sellActiveTickets);
Router.post('/other_htee', ThaiController.getOtherHtee);
Router.post('/other_htee_by_agent', ThaiController.getOtherHteeByAgent);
// Router.get('/other_htee_by_date', ThaiController.getOtherHteeByDate);
Router.post('/other_htee_ledger', ThaiController.getOtherHteeLedger);
Router.post('/create_other_htee', ThaiController.createOtherHtee);
Router.post('/delete_other_htee', ThaiController.deleteOtherHtee);
Router.post('/delete_other_htee_by_agent', ThaiController.deleteOtherHteeByAgent);
Router.post('/remark_other_htee', ThaiController.remarkOtherHtee);
Router.post('/company_other_htee', ThaiController.companyOtherHtee);
module.exports = Router;