const ROUTER =require('express-promise-router')();
const CONTROLLER =require('../controllers/lao');
const SCHEMA =require('../schemas/lao');
const VALIDATOR =require('../../helpers/validator');
ROUTER.get('/settings',CONTROLLER.getSetting);
ROUTER.post('/update_setting',VALIDATOR.validateBody(SCHEMA.lao_setting),CONTROLLER.updateSetting);
ROUTER.post('/create_lao_price_item',VALIDATOR.validateBody(SCHEMA.lao_price_item),CONTROLLER.createLaoPriceItem);
ROUTER.post('/delete_price_item',VALIDATOR.validateBody(SCHEMA.check_id),CONTROLLER.deleteLaoPriceItem);
ROUTER.post('/update_lao_price_item',VALIDATOR.validateBody(SCHEMA.lao_update_price_item),CONTROLLER.updateLaoPriceItem);
ROUTER.post('/check_numbers',VALIDATOR.validateBody(SCHEMA.check_lao_ticket),CONTROLLER.checkLaoNumber);
ROUTER.post('/check_k_numbers',VALIDATOR.validateBody(SCHEMA.check_lao_ticket),CONTROLLER.checkLaoKNumber);
ROUTER.post('/save_numbers',VALIDATOR.validateBody(SCHEMA.save_lao_ticket),CONTROLLER.saveLaoNumber);
ROUTER.post('/save_numbers_k',VALIDATOR.validateBody(SCHEMA.save_lao_ticket),CONTROLLER.saveLaoKNumber);
ROUTER.post('/lao_ticket_ledger',VALIDATOR.validateBody(SCHEMA.check_between_date),CONTROLLER.getLaoTicketLedger);
ROUTER.post('/lao_k_ticket_ledger',VALIDATOR.validateBody(SCHEMA.check_between_date),CONTROLLER.getLaoKTicketLedger);
ROUTER.post('/lao_delete_ticket_ledger',VALIDATOR.validateBody(SCHEMA.check_between_date),CONTROLLER.getLaoDeleteTicketLedger);
ROUTER.post('/lao_k_delete_ticket_ledger',VALIDATOR.validateBody(SCHEMA.check_between_date),CONTROLLER.getLaoKDeleteTicketLedger);
ROUTER.post('/delete_ticket',VALIDATOR.validateBody(SCHEMA.check_id),CONTROLLER.deleteLaoTicket);
ROUTER.post('/delete_k_ticket',VALIDATOR.validateBody(SCHEMA.check_id),CONTROLLER.deleteLaoKTicket);
ROUTER.post('/lao_table_number',VALIDATOR.validateBody(SCHEMA.check_date),CONTROLLER.laoTableNumber);
ROUTER.post('/lao_k_table_number',VALIDATOR.validateBody(SCHEMA.check_date),CONTROLLER.laoKTableNumber);
ROUTER.post('/save_lao_win_number',VALIDATOR.validateBody(SCHEMA.check_win_number),CONTROLLER.saveLaoWinNumber);
ROUTER.get('/win_number_ledger',CONTROLLER.winNumberLedger);
ROUTER.post('/cut_numbers',VALIDATOR.validateBody(SCHEMA.check_cut_date),CONTROLLER.laoCutNumber);
ROUTER.post('/cut_by_name_three_d',VALIDATOR.validateBody(SCHEMA.cut_number_three_d),CONTROLLER.cutByNameThreeD);
ROUTER.post('/cut_by_name',VALIDATOR.validateBody(SCHEMA.cut_number),CONTROLLER.cutByName);
ROUTER.post('/all_cut_numbers',VALIDATOR.validateBody(SCHEMA.check_date),CONTROLLER.laoAllCutNumber);
ROUTER.post('/all_kyat_cut_numbers',VALIDATOR.validateBody(SCHEMA.check_date),CONTROLLER.laoAllKyatCutNumber);
ROUTER.post('/all_cut_win_numbers',VALIDATOR.validateBody(SCHEMA.check_date),CONTROLLER.laoAllCutWinNumbers);
ROUTER.post('/all_cut_win_k_numbers',VALIDATOR.validateBody(SCHEMA.check_date),CONTROLLER.laoAllCutWinKNumbers);
ROUTER.post('/cash_voucher',VALIDATOR.validateBody(SCHEMA.check_id),CONTROLLER.cashVoucher);
ROUTER.post('/cash_k_voucher',VALIDATOR.validateBody(SCHEMA.check_id),CONTROLLER.cashKVoucher);
ROUTER.post('/profit_ledger',VALIDATOR.validateBody(SCHEMA.check_between_date),CONTROLLER.getProfitLedger);
ROUTER.post('/profit_k_ledger',VALIDATOR.validateBody(SCHEMA.check_between_date),CONTROLLER.getProfitKLedger);
ROUTER.post('/lao_final_ledger',VALIDATOR.validateBody(SCHEMA.check_date),CONTROLLER.getLaoFinalLedger);
ROUTER.post('/lao_final_ledger_k',VALIDATOR.validateBody(SCHEMA.check_date),CONTROLLER.getLaoKFinalLedger);
ROUTER.post('/remark',VALIDATOR.validateBody(SCHEMA.check_remark),CONTROLLER.remarkLao);
ROUTER.post('/remark_k',VALIDATOR.validateBody(SCHEMA.check_remark),CONTROLLER.remarkKLao);
ROUTER.post('/balance_ledger',VALIDATOR.validateBody(SCHEMA.check_between_date),CONTROLLER.balanceLedger);
ROUTER.post('/cut_kyat_numbers',VALIDATOR.validateBody(SCHEMA.check_cut_date),CONTROLLER.laoKyatCutNumber);
ROUTER.post('/cut_by_name_three_d_kyat',VALIDATOR.validateBody(SCHEMA.cut_number_three_d),CONTROLLER.cutByNameThreeDKyat);
ROUTER.post('/lao_cash_ledgers',CONTROLLER.laoCashLedgers);
ROUTER.post('/lao_pre_pay_balance',CONTROLLER.laoPrePayBalance);
ROUTER.post('/lao_shop_amount',CONTROLLER.laoShopAmount);
module.exports = ROUTER;

